nodes_to_observer:
  - "/robot_41/master_discovery"
  - "/robot_41/localization_scoring"
  - "/robot_41/triangle_extraction"
  - "/robot_41/robot_state_publisher"
  - "/robot_41/joystick"
  - "/robot_41/fine_positioning"
  - "/robot_41/nav_watchdog"
  - "/robot_41/sicks300"
  - "/robot_41/localize_to_target"
  - "/robot_41/positioning"
  - "/robot_41/parameter_listener"
  - "/robot_41/map_talker"
  - "/robot_41/move_base"
  - "/robot_41/ose800_can_driver"
  - "/robot_41/master_sync_robot"
  - "/robot_41/state_of_charge_node"
  - "/robot_41/reverse_fine_positioning_node"
  - "/robot_41/laser_scan_matching"
  - "/robot_41/agent"
  - "/robot_41/amcl"
  - "/robot_41/imu_calibration"
  - "/tug_observers_cpp_node"
  - "/robot_41/gmapping"
  - "/robot_41/turtlebot_teleop_joystick"
  - "/robot_41/target_filter"
  - "/robot_41/triangle_localization"
  - "/robot_41/laser_calibration"
  - "/robot_41/battery_lights"
  - "/robot_41/battery_status_logger_test_node"
  - "/robot_41/cmd_vel_mux"
  - "/robot_41/map_to_local_map_pub"
  - "/robot_41/system_monitor"
