(cl:defpackage tug_diagnosis_msgs-msg
  (:use )
  (:export
   "<CONFIGURATION>"
   "CONFIGURATION"
   "<DIAGNOSIS>"
   "DIAGNOSIS"
   "<DIAGNOSIS_SET>"
   "DIAGNOSIS_SET"
   "<NODE_CONFIGURATION>"
   "NODE_CONFIGURATION"
   "<OBSERVER_CONFIGURATION>"
   "OBSERVER_CONFIGURATION"
   "<RESOURCE_MODE_ASSIGNEMENT>"
   "RESOURCE_MODE_ASSIGNEMENT"
  ))

