// Generated by gencpp from file tug_reporter/SetString.msg
// DO NOT EDIT!


#ifndef TUG_REPORTER_MESSAGE_SETSTRING_H
#define TUG_REPORTER_MESSAGE_SETSTRING_H

#include <ros/service_traits.h>


#include <tug_reporter/SetStringRequest.h>
#include <tug_reporter/SetStringResponse.h>


namespace tug_reporter
{

struct SetString
{

typedef SetStringRequest Request;
typedef SetStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetString
} // namespace tug_reporter


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tug_reporter::SetString > {
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::tug_reporter::SetString&) { return value(); }
};

template<>
struct DataType< ::tug_reporter::SetString > {
  static const char* value()
  {
    return "tug_reporter/SetString";
  }

  static const char* value(const ::tug_reporter::SetString&) { return value(); }
};


// service_traits::MD5Sum< ::tug_reporter::SetStringRequest> should match 
// service_traits::MD5Sum< ::tug_reporter::SetString > 
template<>
struct MD5Sum< ::tug_reporter::SetStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tug_reporter::SetString >::value();
  }
  static const char* value(const ::tug_reporter::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_reporter::SetStringRequest> should match 
// service_traits::DataType< ::tug_reporter::SetString > 
template<>
struct DataType< ::tug_reporter::SetStringRequest>
{
  static const char* value()
  {
    return DataType< ::tug_reporter::SetString >::value();
  }
  static const char* value(const ::tug_reporter::SetStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tug_reporter::SetStringResponse> should match 
// service_traits::MD5Sum< ::tug_reporter::SetString > 
template<>
struct MD5Sum< ::tug_reporter::SetStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tug_reporter::SetString >::value();
  }
  static const char* value(const ::tug_reporter::SetStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_reporter::SetStringResponse> should match 
// service_traits::DataType< ::tug_reporter::SetString > 
template<>
struct DataType< ::tug_reporter::SetStringResponse>
{
  static const char* value()
  {
    return DataType< ::tug_reporter::SetString >::value();
  }
  static const char* value(const ::tug_reporter::SetStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUG_REPORTER_MESSAGE_SETSTRING_H
