# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tug_diagnosis_msgs/diagnosis.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tug_diagnosis_msgs.msg

class diagnosis(genpy.Message):
  _md5sum = "52161f8a0d1740c6fc459d4f815e3e6d"
  _type = "tug_diagnosis_msgs/diagnosis"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """resource_mode_assignement[] diagnosis

================================================================================
MSG: tug_diagnosis_msgs/resource_mode_assignement
string resource
string mode_msg
int32 mode
int32 GENERAL_OK=0
int32 GENERAL_ERROR=-1
"""
  __slots__ = ['diagnosis']
  _slot_types = ['tug_diagnosis_msgs/resource_mode_assignement[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       diagnosis

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(diagnosis, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.diagnosis is None:
        self.diagnosis = []
    else:
      self.diagnosis = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.diagnosis)
      buff.write(_struct_I.pack(length))
      for val1 in self.diagnosis:
        _x = val1.resource
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.mode_msg
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_i().pack(val1.mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.diagnosis is None:
        self.diagnosis = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.diagnosis = []
      for i in range(0, length):
        val1 = tug_diagnosis_msgs.msg.resource_mode_assignement()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.resource = str[start:end].decode('utf-8')
        else:
          val1.resource = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.mode_msg = str[start:end].decode('utf-8')
        else:
          val1.mode_msg = str[start:end]
        start = end
        end += 4
        (val1.mode,) = _get_struct_i().unpack(str[start:end])
        self.diagnosis.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.diagnosis)
      buff.write(_struct_I.pack(length))
      for val1 in self.diagnosis:
        _x = val1.resource
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1.mode_msg
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        buff.write(_get_struct_i().pack(val1.mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.diagnosis is None:
        self.diagnosis = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.diagnosis = []
      for i in range(0, length):
        val1 = tug_diagnosis_msgs.msg.resource_mode_assignement()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.resource = str[start:end].decode('utf-8')
        else:
          val1.resource = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.mode_msg = str[start:end].decode('utf-8')
        else:
          val1.mode_msg = str[start:end]
        start = end
        end += 4
        (val1.mode,) = _get_struct_i().unpack(str[start:end])
        self.diagnosis.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
