// Generated by gencpp from file tug_resource_monitor/NodesInfo.msg
// DO NOT EDIT!


#ifndef TUG_RESOURCE_MONITOR_MESSAGE_NODESINFO_H
#define TUG_RESOURCE_MONITOR_MESSAGE_NODESINFO_H

#include <ros/service_traits.h>


#include <tug_resource_monitor/NodesInfoRequest.h>
#include <tug_resource_monitor/NodesInfoResponse.h>


namespace tug_resource_monitor
{

struct NodesInfo
{

typedef NodesInfoRequest Request;
typedef NodesInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NodesInfo
} // namespace tug_resource_monitor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tug_resource_monitor::NodesInfo > {
  static const char* value()
  {
    return "42c13fd17030d24481c0409739ac5ae7";
  }

  static const char* value(const ::tug_resource_monitor::NodesInfo&) { return value(); }
};

template<>
struct DataType< ::tug_resource_monitor::NodesInfo > {
  static const char* value()
  {
    return "tug_resource_monitor/NodesInfo";
  }

  static const char* value(const ::tug_resource_monitor::NodesInfo&) { return value(); }
};


// service_traits::MD5Sum< ::tug_resource_monitor::NodesInfoRequest> should match 
// service_traits::MD5Sum< ::tug_resource_monitor::NodesInfo > 
template<>
struct MD5Sum< ::tug_resource_monitor::NodesInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tug_resource_monitor::NodesInfo >::value();
  }
  static const char* value(const ::tug_resource_monitor::NodesInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_resource_monitor::NodesInfoRequest> should match 
// service_traits::DataType< ::tug_resource_monitor::NodesInfo > 
template<>
struct DataType< ::tug_resource_monitor::NodesInfoRequest>
{
  static const char* value()
  {
    return DataType< ::tug_resource_monitor::NodesInfo >::value();
  }
  static const char* value(const ::tug_resource_monitor::NodesInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tug_resource_monitor::NodesInfoResponse> should match 
// service_traits::MD5Sum< ::tug_resource_monitor::NodesInfo > 
template<>
struct MD5Sum< ::tug_resource_monitor::NodesInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tug_resource_monitor::NodesInfo >::value();
  }
  static const char* value(const ::tug_resource_monitor::NodesInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tug_resource_monitor::NodesInfoResponse> should match 
// service_traits::DataType< ::tug_resource_monitor::NodesInfo > 
template<>
struct DataType< ::tug_resource_monitor::NodesInfoResponse>
{
  static const char* value()
  {
    return DataType< ::tug_resource_monitor::NodesInfo >::value();
  }
  static const char* value(const ::tug_resource_monitor::NodesInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUG_RESOURCE_MONITOR_MESSAGE_NODESINFO_H
