// Generated by gencpp from file tug_observers_msgs/observer_info.msg
// DO NOT EDIT!


#ifndef TUG_OBSERVERS_MSGS_MESSAGE_OBSERVER_INFO_H
#define TUG_OBSERVERS_MSGS_MESSAGE_OBSERVER_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tug_observers_msgs/observation_info.h>

namespace tug_observers_msgs
{
template <class ContainerAllocator>
struct observer_info_
{
  typedef observer_info_<ContainerAllocator> Type;

  observer_info_()
    : observation_infos()  {
    }
  observer_info_(const ContainerAllocator& _alloc)
    : observation_infos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::tug_observers_msgs::observation_info_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tug_observers_msgs::observation_info_<ContainerAllocator> >::other >  _observation_infos_type;
  _observation_infos_type observation_infos;





  typedef boost::shared_ptr< ::tug_observers_msgs::observer_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_observers_msgs::observer_info_<ContainerAllocator> const> ConstPtr;

}; // struct observer_info_

typedef ::tug_observers_msgs::observer_info_<std::allocator<void> > observer_info;

typedef boost::shared_ptr< ::tug_observers_msgs::observer_info > observer_infoPtr;
typedef boost::shared_ptr< ::tug_observers_msgs::observer_info const> observer_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_observers_msgs::observer_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_observers_msgs::observer_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_observers_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tug_observers_msgs': ['/home/anna/catkin_ws/src/model_based_diagnosis/tug_observers/tug_observers_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_observers_msgs::observer_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_observers_msgs::observer_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_observers_msgs::observer_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_observers_msgs::observer_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_observers_msgs::observer_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_observers_msgs::observer_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_observers_msgs::observer_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38c26f4d3dc2b7fc8f36eef35fb2083c";
  }

  static const char* value(const ::tug_observers_msgs::observer_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38c26f4d3dc2b7fcULL;
  static const uint64_t static_value2 = 0x8f36eef35fb2083cULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_observers_msgs::observer_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_observers_msgs/observer_info";
  }

  static const char* value(const ::tug_observers_msgs::observer_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_observers_msgs::observer_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "observation_info[] observation_infos\n\
\n\
================================================================================\n\
MSG: tug_observers_msgs/observation_info\n\
Header header\n\
string type\n\
string resource\n\
observation[] observation\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: tug_observers_msgs/observation\n\
string observation_msg\n\
string verbose_observation_msg\n\
int32 observation\n\
int32 GENERAL_OK=0\n\
int32 GENERAL_ERROR=-1\n\
int32 NO_STATE_FITS=-2\n\
int32 NOT_AVAILABLE=-3\n\
int32 TIMEOUT=-4\n\
";
  }

  static const char* value(const ::tug_observers_msgs::observer_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_observers_msgs::observer_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.observation_infos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct observer_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_observers_msgs::observer_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_observers_msgs::observer_info_<ContainerAllocator>& v)
  {
    s << indent << "observation_infos[]" << std::endl;
    for (size_t i = 0; i < v.observation_infos.size(); ++i)
    {
      s << indent << "  observation_infos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tug_observers_msgs::observation_info_<ContainerAllocator> >::stream(s, indent + "    ", v.observation_infos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_OBSERVERS_MSGS_MESSAGE_OBSERVER_INFO_H
