// Generated by gencpp from file tug_observers_msgs/observation_info.msg
// DO NOT EDIT!


#ifndef TUG_OBSERVERS_MSGS_MESSAGE_OBSERVATION_INFO_H
#define TUG_OBSERVERS_MSGS_MESSAGE_OBSERVATION_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tug_observers_msgs/observation.h>

namespace tug_observers_msgs
{
template <class ContainerAllocator>
struct observation_info_
{
  typedef observation_info_<ContainerAllocator> Type;

  observation_info_()
    : header()
    , type()
    , resource()
    , observation()  {
    }
  observation_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(_alloc)
    , resource(_alloc)
    , observation(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _resource_type;
  _resource_type resource;

   typedef std::vector< ::tug_observers_msgs::observation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tug_observers_msgs::observation_<ContainerAllocator> >::other >  _observation_type;
  _observation_type observation;





  typedef boost::shared_ptr< ::tug_observers_msgs::observation_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_observers_msgs::observation_info_<ContainerAllocator> const> ConstPtr;

}; // struct observation_info_

typedef ::tug_observers_msgs::observation_info_<std::allocator<void> > observation_info;

typedef boost::shared_ptr< ::tug_observers_msgs::observation_info > observation_infoPtr;
typedef boost::shared_ptr< ::tug_observers_msgs::observation_info const> observation_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_observers_msgs::observation_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_observers_msgs::observation_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_observers_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'tug_observers_msgs': ['/home/anna/catkin_ws/src/model_based_diagnosis/tug_observers/tug_observers_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_observers_msgs::observation_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_observers_msgs::observation_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_observers_msgs::observation_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_observers_msgs::observation_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_observers_msgs::observation_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_observers_msgs::observation_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_observers_msgs::observation_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "920b39a3d493095fc494ca757b21762f";
  }

  static const char* value(const ::tug_observers_msgs::observation_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x920b39a3d493095fULL;
  static const uint64_t static_value2 = 0xc494ca757b21762fULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_observers_msgs::observation_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_observers_msgs/observation_info";
  }

  static const char* value(const ::tug_observers_msgs::observation_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_observers_msgs::observation_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string type\n\
string resource\n\
observation[] observation\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: tug_observers_msgs/observation\n\
string observation_msg\n\
string verbose_observation_msg\n\
int32 observation\n\
int32 GENERAL_OK=0\n\
int32 GENERAL_ERROR=-1\n\
int32 NO_STATE_FITS=-2\n\
int32 NOT_AVAILABLE=-3\n\
int32 TIMEOUT=-4\n\
";
  }

  static const char* value(const ::tug_observers_msgs::observation_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_observers_msgs::observation_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.resource);
      stream.next(m.observation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct observation_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_observers_msgs::observation_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_observers_msgs::observation_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "resource: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.resource);
    s << indent << "observation[]" << std::endl;
    for (size_t i = 0; i < v.observation.size(); ++i)
    {
      s << indent << "  observation[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tug_observers_msgs::observation_<ContainerAllocator> >::stream(s, indent + "    ", v.observation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_OBSERVERS_MSGS_MESSAGE_OBSERVATION_INFO_H
