setup:
- type: moveing
  moveings:
  - source:
      type: imu
      topic: /imu_data
    x_filter:
      type: nofilter
    y_filter:
      type: nofilter
    use_yaw: true
    rot_x_filter:
      type: nofilter
    rot_y_filter:
      type: nofilter
    rot_z_filter:
      type: nofilter
    states:
    - state: '1'
      number: 1
      x:
        type: nominal_value
        value:    
          type: gauss
          mean: 0.0
          std_deviation: 0.2
      y:
        type: nominal_value
        value:    
          type: gauss
          mean: 0.0
          std_deviation: 0.2
      rot_x:
        type: nominal_value
        value:    
          type: gauss
          mean: 0.0
          std_deviation: 0.01
      rot_y:
        type: nominal_value
        value:    
          type: gauss
          mean: 0.0
          std_deviation: 0.01
      rot_z:
        type: nominal_value
        value:    
          type: gauss
          mean: 0.0
          std_deviation: 0.2
