setup:
- type: velocity
  correlations:
  - source_A:
      type: odometry
      topic: /robot_41/odom
    source_B:
      type: twist
      topic: /robot_41/cmd_vel
    x_filter:
      type: mean
      window_size: 50
    y_filter:
      type: mean
      window_size: 50
    use_yaw: true
    rot_x_filter:
      type: mean
      window_size: 50
    rot_y_filter:
      type: mean
      window_size: 50
    rot_z_filter:
      type: mean
      window_size: 50
    states:
    - state: '1'
      number: 1
      x:
        type: nominal_value
        value:    
          type: gauss
          mean: 0.0
          std_deviation: 0.2
      y:
        type: nominal_value
        value:    
          type: gauss
          mean: 0.0
          std_deviation: 0.2
      rot_x:
        type: nominal_value
        value:    
          type: gauss
          mean: 0.0
          std_deviation: 0.01
      rot_y:
        type: nominal_value
        value:    
          type: gauss
          mean: 0.0
          std_deviation: 0.01
      rot_z:
        type: nominal_value
        value:    
          type: gauss
          mean: 0.0
          std_deviation: 0.2
