########## node1 ##########
setup:
- type: hz
  main_loop_rate: 1.0
  use_global_subscriber: true
  topics:
  - name: /imu_topic
    callerids:
    - callerid: []
      filter:
        type: mean                      #exponentially weighted moving average
        window_size: 10
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
#        decay_rate: 0.05
#        k_size: 10
        deviation_type: std_deviation   # std_deviation, min_max
      states:
      - state: 'student_t'
        number: 1
        frequenzy:
          type: student_t
          true_mean: 0.10
          significance_level: 0.5

  - name: /loam_topic
    callerids:
    - callerid: []
      filter:
        type: mean                      #exponentially weighted moving average
        window_size: 10
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
#        decay_rate: 0.05
#        k_size: 10
        deviation_type: std_deviation   # std_deviation, min_max
      states:
      - state: 'student_t'
        number: 1
        frequenzy:
          type: student_t
          true_mean: 0.10
          significance_level: 0.5

  - name: /odom_topic
    callerids:
    - callerid: []
      filter:
        type: mean                      #exponentially weighted moving average
        window_size: 10
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
#        decay_rate: 0.05
#        k_size: 10
        deviation_type: std_deviation   # std_deviation, min_max
      states:
      - state: 'student_t'
        number: 1
        frequenzy:
          type: student_t
          true_mean: 0.10
          significance_level: 0.5

  - name: /cmd_topic
    callerids:
    - callerid: []
      filter:
        type: mean                      #exponentially weighted moving average
        window_size: 10
        # x = old_x * (1.0 - decay_rate) + new_x * decay_rate
#        decay_rate: 0.05
#        k_size: 10
        deviation_type: std_deviation   # std_deviation, min_max
      states:
      - state: 'student_t'
        number: 1
        frequenzy:
          type: student_t
          true_mean: 0.10
          significance_level: 0.5