(cl:defpackage tug_diagnosis_msgs-srv
  (:use )
  (:export
   "DIAGNOSISCONFIGURATION"
   "<DIAGNOSISCONFIGURATION-REQUEST>"
   "DIAGNOSISCONFIGURATION-REQUEST"
   "<DIAGNOSISCONFIGURATION-RESPONSE>"
   "DIAGNOSISCONFIGURATION-RESPONSE"
  ))

