// Generated by gencpp from file tug_diagnosis_msgs/configuration.msg
// DO NOT EDIT!


#ifndef TUG_DIAGNOSIS_MSGS_MESSAGE_CONFIGURATION_H
#define TUG_DIAGNOSIS_MSGS_MESSAGE_CONFIGURATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tug_diagnosis_msgs/node_configuration.h>
#include <tug_diagnosis_msgs/observer_configuration.h>

namespace tug_diagnosis_msgs
{
template <class ContainerAllocator>
struct configuration_
{
  typedef configuration_<ContainerAllocator> Type;

  configuration_()
    : nodes()
    , observers()  {
    }
  configuration_(const ContainerAllocator& _alloc)
    : nodes(_alloc)
    , observers(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >::other >  _nodes_type;
  _nodes_type nodes;

   typedef std::vector< ::tug_diagnosis_msgs::observer_configuration_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tug_diagnosis_msgs::observer_configuration_<ContainerAllocator> >::other >  _observers_type;
  _observers_type observers;





  typedef boost::shared_ptr< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> const> ConstPtr;

}; // struct configuration_

typedef ::tug_diagnosis_msgs::configuration_<std::allocator<void> > configuration;

typedef boost::shared_ptr< ::tug_diagnosis_msgs::configuration > configurationPtr;
typedef boost::shared_ptr< ::tug_diagnosis_msgs::configuration const> configurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_diagnosis_msgs::configuration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_diagnosis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tug_diagnosis_msgs': ['/home/anna/catkin_ws/src/model_based_diagnosis/tug_diagnosis/tug_diagnosis_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cadde33865d5cf9cef30c348d588d747";
  }

  static const char* value(const ::tug_diagnosis_msgs::configuration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcadde33865d5cf9cULL;
  static const uint64_t static_value2 = 0xef30c348d588d747ULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_diagnosis_msgs/configuration";
  }

  static const char* value(const ::tug_diagnosis_msgs::configuration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_configuration[] nodes\n\
observer_configuration[] observers\n\
\n\
================================================================================\n\
MSG: tug_diagnosis_msgs/node_configuration\n\
string name\n\
string[] sub_topic\n\
string[] pub_topic\n\
\n\
================================================================================\n\
MSG: tug_diagnosis_msgs/observer_configuration\n\
string type\n\
string[] resource\n\
";
  }

  static const char* value(const ::tug_diagnosis_msgs::configuration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodes);
      stream.next(m.observers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct configuration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_diagnosis_msgs::configuration_<ContainerAllocator>& v)
  {
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >::stream(s, indent + "    ", v.nodes[i]);
    }
    s << indent << "observers[]" << std::endl;
    for (size_t i = 0; i < v.observers.size(); ++i)
    {
      s << indent << "  observers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tug_diagnosis_msgs::observer_configuration_<ContainerAllocator> >::stream(s, indent + "    ", v.observers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_DIAGNOSIS_MSGS_MESSAGE_CONFIGURATION_H
