// Generated by gencpp from file tug_diagnosis_msgs/DiagnosisConfigurationRequest.msg
// DO NOT EDIT!


#ifndef TUG_DIAGNOSIS_MSGS_MESSAGE_DIAGNOSISCONFIGURATIONREQUEST_H
#define TUG_DIAGNOSIS_MSGS_MESSAGE_DIAGNOSISCONFIGURATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tug_diagnosis_msgs/configuration.h>

namespace tug_diagnosis_msgs
{
template <class ContainerAllocator>
struct DiagnosisConfigurationRequest_
{
  typedef DiagnosisConfigurationRequest_<ContainerAllocator> Type;

  DiagnosisConfigurationRequest_()
    : config()
    , action(0)  {
    }
  DiagnosisConfigurationRequest_(const ContainerAllocator& _alloc)
    : config(_alloc)
    , action(0)  {
  (void)_alloc;
    }



   typedef  ::tug_diagnosis_msgs::configuration_<ContainerAllocator>  _config_type;
  _config_type config;

   typedef int32_t _action_type;
  _action_type action;



  enum {
    ADD = 1,
    REMOVE = 2,
    SET = 3,
    UPDATE = 4,
  };


  typedef boost::shared_ptr< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DiagnosisConfigurationRequest_

typedef ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<std::allocator<void> > DiagnosisConfigurationRequest;

typedef boost::shared_ptr< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest > DiagnosisConfigurationRequestPtr;
typedef boost::shared_ptr< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest const> DiagnosisConfigurationRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_diagnosis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tug_diagnosis_msgs': ['/home/anna/catkin_ws/src/model_based_diagnosis/tug_diagnosis/tug_diagnosis_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3d76205ac43f0b93af9b41d85fffda2";
  }

  static const char* value(const ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3d76205ac43f0b9ULL;
  static const uint64_t static_value2 = 0x3af9b41d85fffda2ULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_diagnosis_msgs/DiagnosisConfigurationRequest";
  }

  static const char* value(const ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
configuration config\n\
\n\
\n\
int32 action\n\
int32 ADD=1\n\
int32 REMOVE=2\n\
int32 SET=3\n\
int32 UPDATE=4\n\
\n\
\n\
================================================================================\n\
MSG: tug_diagnosis_msgs/configuration\n\
node_configuration[] nodes\n\
observer_configuration[] observers\n\
\n\
================================================================================\n\
MSG: tug_diagnosis_msgs/node_configuration\n\
string name\n\
string[] sub_topic\n\
string[] pub_topic\n\
\n\
================================================================================\n\
MSG: tug_diagnosis_msgs/observer_configuration\n\
string type\n\
string[] resource\n\
";
  }

  static const char* value(const ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.config);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiagnosisConfigurationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_diagnosis_msgs::DiagnosisConfigurationRequest_<ContainerAllocator>& v)
  {
    s << indent << "config: ";
    s << std::endl;
    Printer< ::tug_diagnosis_msgs::configuration_<ContainerAllocator> >::stream(s, indent + "  ", v.config);
    s << indent << "action: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_DIAGNOSIS_MSGS_MESSAGE_DIAGNOSISCONFIGURATIONREQUEST_H
