// Generated by gencpp from file tug_diagnosis_msgs/DiagnosisConfigurationResponse.msg
// DO NOT EDIT!


#ifndef TUG_DIAGNOSIS_MSGS_MESSAGE_DIAGNOSISCONFIGURATIONRESPONSE_H
#define TUG_DIAGNOSIS_MSGS_MESSAGE_DIAGNOSISCONFIGURATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_diagnosis_msgs
{
template <class ContainerAllocator>
struct DiagnosisConfigurationResponse_
{
  typedef DiagnosisConfigurationResponse_<ContainerAllocator> Type;

  DiagnosisConfigurationResponse_()
    : errorcode(0)
    , error_msg()  {
    }
  DiagnosisConfigurationResponse_(const ContainerAllocator& _alloc)
    : errorcode(0)
    , error_msg(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _errorcode_type;
  _errorcode_type errorcode;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_msg_type;
  _error_msg_type error_msg;



  enum {
    NO_ERROR = 0,
    GENERAL_ERROR = -1,
    CONFIG_INVALID = -2,
  };


  typedef boost::shared_ptr< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DiagnosisConfigurationResponse_

typedef ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<std::allocator<void> > DiagnosisConfigurationResponse;

typedef boost::shared_ptr< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse > DiagnosisConfigurationResponsePtr;
typedef boost::shared_ptr< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse const> DiagnosisConfigurationResponseConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_diagnosis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tug_diagnosis_msgs': ['/home/anna/catkin_ws/src/model_based_diagnosis/tug_diagnosis/tug_diagnosis_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "831df38a86121a0898c425468fa0cc9d";
  }

  static const char* value(const ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x831df38a86121a08ULL;
  static const uint64_t static_value2 = 0x98c425468fa0cc9dULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_diagnosis_msgs/DiagnosisConfigurationResponse";
  }

  static const char* value(const ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
int32 errorcode\n\
string error_msg\n\
int32 NO_ERROR=0\n\
int32 GENERAL_ERROR=-1\n\
int32 CONFIG_INVALID=-2\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.errorcode);
      stream.next(m.error_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DiagnosisConfigurationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_diagnosis_msgs::DiagnosisConfigurationResponse_<ContainerAllocator>& v)
  {
    s << indent << "errorcode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.errorcode);
    s << indent << "error_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_DIAGNOSIS_MSGS_MESSAGE_DIAGNOSISCONFIGURATIONRESPONSE_H
