// Generated by gencpp from file tug_diagnosis_msgs/node_configuration.msg
// DO NOT EDIT!


#ifndef TUG_DIAGNOSIS_MSGS_MESSAGE_NODE_CONFIGURATION_H
#define TUG_DIAGNOSIS_MSGS_MESSAGE_NODE_CONFIGURATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_diagnosis_msgs
{
template <class ContainerAllocator>
struct node_configuration_
{
  typedef node_configuration_<ContainerAllocator> Type;

  node_configuration_()
    : name()
    , sub_topic()
    , pub_topic()  {
    }
  node_configuration_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , sub_topic(_alloc)
    , pub_topic(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _sub_topic_type;
  _sub_topic_type sub_topic;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _pub_topic_type;
  _pub_topic_type pub_topic;





  typedef boost::shared_ptr< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> const> ConstPtr;

}; // struct node_configuration_

typedef ::tug_diagnosis_msgs::node_configuration_<std::allocator<void> > node_configuration;

typedef boost::shared_ptr< ::tug_diagnosis_msgs::node_configuration > node_configurationPtr;
typedef boost::shared_ptr< ::tug_diagnosis_msgs::node_configuration const> node_configurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_diagnosis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tug_diagnosis_msgs': ['/home/anna/catkin_ws/src/model_based_diagnosis/tug_diagnosis/tug_diagnosis_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d437a072fcff0973a4326ed765667e76";
  }

  static const char* value(const ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd437a072fcff0973ULL;
  static const uint64_t static_value2 = 0xa4326ed765667e76ULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_diagnosis_msgs/node_configuration";
  }

  static const char* value(const ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string[] sub_topic\n\
string[] pub_topic\n\
";
  }

  static const char* value(const ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.sub_topic);
      stream.next(m.pub_topic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node_configuration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_diagnosis_msgs::node_configuration_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "sub_topic[]" << std::endl;
    for (size_t i = 0; i < v.sub_topic.size(); ++i)
    {
      s << indent << "  sub_topic[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sub_topic[i]);
    }
    s << indent << "pub_topic[]" << std::endl;
    for (size_t i = 0; i < v.pub_topic.size(); ++i)
    {
      s << indent << "  pub_topic[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pub_topic[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_DIAGNOSIS_MSGS_MESSAGE_NODE_CONFIGURATION_H
