// Generated by gencpp from file tug_diagnosis_msgs/resource_mode_assignement.msg
// DO NOT EDIT!


#ifndef TUG_DIAGNOSIS_MSGS_MESSAGE_RESOURCE_MODE_ASSIGNEMENT_H
#define TUG_DIAGNOSIS_MSGS_MESSAGE_RESOURCE_MODE_ASSIGNEMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tug_diagnosis_msgs
{
template <class ContainerAllocator>
struct resource_mode_assignement_
{
  typedef resource_mode_assignement_<ContainerAllocator> Type;

  resource_mode_assignement_()
    : resource()
    , mode_msg()
    , mode(0)  {
    }
  resource_mode_assignement_(const ContainerAllocator& _alloc)
    : resource(_alloc)
    , mode_msg(_alloc)
    , mode(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _resource_type;
  _resource_type resource;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_msg_type;
  _mode_msg_type mode_msg;

   typedef int32_t _mode_type;
  _mode_type mode;



  enum {
    GENERAL_OK = 0,
    GENERAL_ERROR = -1,
  };


  typedef boost::shared_ptr< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> const> ConstPtr;

}; // struct resource_mode_assignement_

typedef ::tug_diagnosis_msgs::resource_mode_assignement_<std::allocator<void> > resource_mode_assignement;

typedef boost::shared_ptr< ::tug_diagnosis_msgs::resource_mode_assignement > resource_mode_assignementPtr;
typedef boost::shared_ptr< ::tug_diagnosis_msgs::resource_mode_assignement const> resource_mode_assignementConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tug_diagnosis_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'tug_diagnosis_msgs': ['/home/anna/catkin_ws/src/model_based_diagnosis/tug_diagnosis/tug_diagnosis_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bb0fd0cf9c222fef578a66ea18f38c0";
  }

  static const char* value(const ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bb0fd0cf9c222feULL;
  static const uint64_t static_value2 = 0xf578a66ea18f38c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tug_diagnosis_msgs/resource_mode_assignement";
  }

  static const char* value(const ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string resource\n\
string mode_msg\n\
int32 mode\n\
int32 GENERAL_OK=0\n\
int32 GENERAL_ERROR=-1\n\
";
  }

  static const char* value(const ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resource);
      stream.next(m.mode_msg);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct resource_mode_assignement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tug_diagnosis_msgs::resource_mode_assignement_<ContainerAllocator>& v)
  {
    s << indent << "resource: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.resource);
    s << indent << "mode_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode_msg);
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUG_DIAGNOSIS_MSGS_MESSAGE_RESOURCE_MODE_ASSIGNEMENT_H
